# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integrity Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_VERSION: 2.2.0 
      CONSTRAINT_URL: "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.0/constraints-3.9.txt" 
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "apache-airflow[postgres,aws,slack,snowflake]==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
        pip install pytest pytest-helpers-namespace
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Init Airflow
      run: |
        airflow db init
        airflow users create \
          --username admin \
          --firstname Peter \
          --lastname Parker \
          --role Admin \
          --email spiderman@superhero.org \
          --password admin 
    - name: Test with pytest
      run: |
        pytest -vv test/dags/
